pipeline {
    agent any
    stages {
        stage('Clean up') {
            steps {
                cleanWs()
            }
        }
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
        }
    }
}
